# Generated by Django 4.1.2 on 2022-11-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_episodio'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='num_ep',
            field=models.IntegerField(default=1, max_length=200),
        ),
    ]
