# Generated by Django 4.1.2 on 2022-11-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0003_episodio_num_ep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodio',
            name='num_ep',
            field=models.IntegerField(default=1),
        ),
    ]
