# Generated by Django 4.1.2 on 2022-11-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0005_subfilms_alter_episodio_num_ep'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subfilms',
        ),
    ]
