# Generated by Django 4.1.2 on 2022-11-15 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0007_episodio_visualizacoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episodio',
            old_name='visualizacoes',
            new_name='visualizacoes_ep',
        ),
    ]
