# Generated by Django 4.1.2 on 2022-11-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0008_rename_visualizacoes_episodio_visualizacoes_ep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodio',
            name='id',
        ),
        migrations.AlterField(
            model_name='episodio',
            name='num_ep',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
