# Generated by Django 4.1.2 on 2022-11-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0009_remove_episodio_id_alter_episodio_num_ep'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episodio',
            name='num_ep',
            field=models.IntegerField(default=0),
        ),
    ]
